QUESTIONS = {
    1: {"savol": "O‘rnatiladigan tizim nima?",
        "variantlar": {"A": "Maxsus vazifalar uchun mo‘ljallangan komputer tizimi", "B": "Umumiy maqsadli kompyuter",
                       "C": "Faqat tarmoq qurilmasi", "D": "Faqat sensor tizimi"}, "javob": "A"},
    2: {"savol": "Quyidagilardan qaysi biri o‘rnatiladigan tizimlarning asosiy xususiyati emas?",
        "variantlar": {"A": "Cheksiz umumiy maqsadli hisoblash quvvati", "B": "Real vaqt rejimida ishlash",
                       "C": "Ixchamlik", "D": "Ishonchlilik"}, "javob": "A"},
    3: {"savol": "Real vaqt tizimida “to‘g‘ri javob kechikdi = noto‘g‘ri” tushunchasi qaysi printsipga oid?",
        "variantlar": {"A": "Kafolatlangan etibor vaqti", "B": "Ishonchlilik", "C": "Yashovchanlik",
                       "D": "Ko‘p masalalik"}, "javob": "A"},
    4: {"savol": "Qattiq real vaqt tizimi (hard real-time) xususiyati nima?",
        "variantlar": {"A": "Vaqt talablariga rioya qilmaslik falokatli oqibatlarga olib keladi",
                       "B": "Javobni kechiksada, tizim ishlashda davom etadi",
                       "C": "Faqat moliyaviy jarayonlarni boshqaradi",
                       "D": "Faqat video ishlov berish uchun mo‘ljallangan"}, "javob": "A"},
    5: {"savol": "Yumshoq real vaqt tizimi (soft real-time) uchun to‘g‘ri bayon qaysi?",
        "variantlar": {"A": "Kadrlarni o‘tkazib yuborish evaziga javob berish mumkin",
                       "B": "Barcha operatsiyalar qat’iy stolga asoslangan",
                       "C": "Javob kechiksa, butun tizim to‘xtaydi", "D": "Faqat harbiy maqsadlarda ishlatiladi"},
        "javob": "A"},
    6: {
        "savol": "O‘rnatiladigan tizimlarni boshqariluvchi ob’ektga singish darajasiga qarab tasniflanganda qaysi guruhga ajratiladi?",
        "variantlar": {"A": "Axborot boshqaruv tizimlari, tarmoqli va kiberfizik tizimlar",
                       "B": "Faqat axborot tizimlari", "C": "Faqat kiberfizik tizimlar",
                       "D": "Faqat taqsimlangan tizimlar"}, "javob": "A"},
    7: {"savol": "Quyidagi indikatorlardan qaysi biri ishonchlilikni o‘lchash imkoniga ega?",
        "variantlar": {"A": "Tayyorlik koeffitsienti", "B": "Buzilishlarning tabiati",
                       "C": "Element bazasining zichligi", "D": "Platformaning turliligi"}, "javob": "A"},
    8: {"savol": "Yashovchanlik (resilience) atamasi nimani anglatadi?",
        "variantlar": {"A": "Nosozlik holatida ham ishlashni saqlab qolish qobiliyati", "B": "Faqat tezlikni",
                       "C": "Dizaynning chiroyliligi", "D": "Faqat tarmoqqa ulanishni"}, "javob": "A"},
    9: {"savol": "O‘rnatiladigan tizimda “etibor vaqti” deganda nimani tushunamiz?",
        "variantlar": {"A": "Datchikdan signal olib, javob uzatilgunga qadar bo‘lgan vaqt",
                       "B": "Tarmoq ulanish tezligi", "C": "Operatsion tizimning versiyasi",
                       "D": "Qurilmaning og‘irligi"}, "javob": "A"},
    10: {"savol": "Platforma turlariga quyidagilardan qaysi misol kiradi?",
         "variantlar": {"A": "FPGA va ASIC", "B": "Desktop kompyuter", "C": "Faqat smartfon", "D": "Faqat serverlar"},
         "javob": "A"},
    11: {"savol": "“Ko‘p masalalik” nima bilan bog‘liq?",
         "variantlar": {"A": "Bir nechta vazifalarni parallel bajara olish qobiliyati",
                        "B": "Tizimning bitta vazifa bajarishi", "C": "Faqat sensor signallarini o‘qishi",
                        "D": "Faqat bitta operatsion tizimni ishlatishi"}, "javob": "A"},
    12: {"savol": "Tarmoqli o‘rnatilgan tizim (Networked Embedded System) nima?",
         "variantlar": {"A": "Bir nechta o‘rnatilgan tugunlar tarmog‘i orqali ishlaydigan tizim",
                        "B": "Faqat offline ishlaydi", "C": "Faqat ayrim ma’lumotlarni saqlaydi",
                        "D": "Faqat bitta sensor tizimidan iborat"}, "javob": "A"},
    13: {"savol": "Kiberfizik tizim (CPS) asosiy xususiyati?",
         "variantlar": {"A": "Fizik dunyo bilan uzviy bog‘lanish va boshqaruv funktsiyasi",
                        "B": "Faqat fizik modelni nazorat qilmaydi", "C": "Faqat moliyaviy hisob-kitoblar uchun",
                        "D": "Faqat video oqimini uzatadi"}, "javob": "A"},
    14: {"savol": "O‘rnatiladigan tizimlarni koʻrsatkichlari qatorida nimalar bor?",
         "variantlar": {"A": "Ishonchlilik, yashovchanlik, ixchamlik, real vaqt rejimi",
                        "B": "Faqat apparat zaryadlanishi", "C": "Faqat dasturiy ta’minot versiyasi",
                        "D": "Faqat ulangan tarmoq soni"}, "javob": "A"},
    15: {"savol": "“Integral mikrosxemalar va mikroprotsessorlar” qachon keng ommalashgan?",
         "variantlar": {"A": "1970-yillarda", "B": "1950-yillarda", "C": "1990-yillarda", "D": "2000-yillarda"},
         "javob": "A"},
    16: {"savol": "O‘rnatiladigan tizimlarda operator ishtirok etishi cheklangan tizim qaysi?",
         "variantlar": {"A": "Avtomatik tizim", "B": "Avtomatlashtirilgan tizim", "C": "Qo‘lda boshqariladigan tizim",
                        "D": "Hisoblash tizimi"}, "javob": "A"},
    17: {"savol": "Buzilish turiga koʻra “to‘satdan buzilish” nimani anglatadi?",
         "variantlar": {"A": "Ko‘rsatkichlar keskin o‘zgarishi bilan yuzaga keladigan buzilish",
                        "B": "Elementlarning noto‘g‘ri joylanishi", "C": "Sekin asta eskirish natijasida",
                        "D": "Faqat operator xatosi"}, "javob": "A"},
    18: {"savol": "“Buyurtmali juda katta integral sxema” deganda nimani tushunasiz?",
         "variantlar": {"A": "FPGA va ASIC", "B": "Faqat DSP", "C": "Faqat mikroprotsessor",
                        "D": "Faqat mobil qurilma"}, "javob": "A"},
    19: {"savol": "Quyidagilardan qaysi biri “avtomatizatsiyalashtirilgan tizim” ta’rifiga kiradi?",
         "variantlar": {"A": "Faqat dastlabki sozlash operator tomonidan – ammo keyinchalik mustaqil",
                        "B": "To‘liq inson ishtirokisiz hech qanday sozlashsiz ishlaydi",
                        "C": "Faqat sensor signallarini qayd etadi", "D": "Faqat mobil ilovalar uchun"}, "javob": "A"},
    20: {"savol": "O‘rnatiladigan tizimlarning rivojlanish bosqichlaridan biri emas?",
         "variantlar": {"A": "Quantum kompyuterlar", "B": "Taqsimlangan boshqaruv tizimlari",
                        "C": "Axborot-boshqaruv tizimlari (ABT)", "D": "Kiberfizik tizimlar"}, "javob": "A"},
    21: {"savol": "O‘rnatilgan tizimlar eng ko‘p qanday sohalarda qo‘llaniladi?",
         "variantlar": {"A": "Avtomobilsozlik, tibbiyot, sanoat", "B": "Sport, madaniyat", "C": "Ta’lim, san’at",
                        "D": "Qurilish, sotsiologiya"}, "javob": "A"},
    22: {"savol": "Analog datchikning eng muhim texnik ko‘rsatgichi nima?",
         "variantlar": {"A": "O‘zgartirish ko‘rsatkichi", "B": "O‘lchash oraliqlari", "C": "O‘lchash tezligi",
                        "D": "Ishlab chiqaruvchisi"}, "javob": "A"},
    23: {"savol": "Oraliq o‘lchov o‘zgartirgichlar nima vazifani bajaradi?",
         "variantlar": {"A": "Signal shaklini saqlab, qiymatini o‘zgartiradi", "B": "Signalni shifrlaydi",
                        "C": "Tizimni o‘chiradi", "D": "Faqat analog signallarni chiqaradi"}, "javob": "A"},
    24: {"savol": "ARO‘ qurilma qanday funktsiyalarni bajaradi?",
         "variantlar": {"A": "Diskretizatsiya, kvantlash va kodlash", "B": "Signalni kuchaytiradi",
                        "C": "Xabar yuboradi", "D": "Bajaruvchi qurilmani boshqaradi"}, "javob": "A"},
    25: {"savol": "RAO‘ qurilmaning vazifasi nima?",
         "variantlar": {"A": "Raqamli kodga mos kuchlanishni hosil qiladi", "B": "Kodni shifrlaydi",
                        "C": "Elektr ta’minotini nazorat qiladi", "D": "Faqat kuchlanishni o‘lchaydi"}, "javob": "A"},
    26: {"savol": "Kommutatorlarning asosiy vazifasi nima?",
         "variantlar": {"A": "Qurilmalarni jismoniy ulash", "B": "Tok manbaini boshqarish", "C": "Qurilmalarni sinash",
                        "D": "Haroratni o‘lchash"}, "javob": "A"},
    27: {"savol": "Multipeksor deganda nima tushuniladi?",
         "variantlar": {"A": "Ko‘p kirishni bitta chiqishga ulash", "B": "Bitta kirishni ko‘p chiqishga ulash",
                        "C": "Signal kuchaytirgich", "D": "Analog o‘zgartirgich"}, "javob": "A"},
    28: {"savol": "RS-232 interfeysi qaysi turga kiradi?",
         "variantlar": {"A": "Ketma-ket tashqi interfeys", "B": "Analog interfeys", "C": "Parallel tizimli interfeys",
                        "D": "Modulli interfeys"}, "javob": "A"},
    29: {"savol": "Ketma-ket RS-485 interfeysining maksimal masofasi qancha?",
         "variantlar": {"A": "1200 m", "B": "500 m", "C": "100 m", "D": "50 m"}, "javob": "A"},
    30: {"savol": "Analog- raqamli o‘zgartirgich qanday asosiy turlarga bo‘linadi?",
         "variantlar": {"A": "Kengaytirib muvozanatlashtirishli, ketma-ketlikda yaqinlashishli, parallel",
                        "B": "Jamlagichli, differensial, kombinatsiyalashgan", "C": "Termik, optik, mexanik",
                        "D": "Signal filtrlari, kuchaytirgichlar, normalizatorlar"}, "javob": "A"},
    31: {"savol": "VME/VXI interfeysi nimaga mo‘ljallangan?",
         "variantlar": {"A": "Magistral-modulli boshqaruv tizimiga", "B": "Video signal uzatishga",
                        "C": "Grafik karta ulashga", "D": "Faqat USB qurilmalariga"}, "javob": "A"},
    32: {"savol": "Industrial Ethernet qanday interfeys turiga kiradi?",
         "variantlar": {"A": "Real vaqtga optimallashtirilgan tarmoq interfeysi", "B": "Parallel",
                        "C": "Analog signal uzatuvchi", "D": "Sanoatdagi optik kabel interfeysi"}, "javob": "A"},
    33: {"savol": "HART interfeysi qanday signalni uzata oladi?",
         "variantlar": {"A": "Analog va raqamli", "B": "Faqat analog", "C": "Faqat raqamli", "D": "Faqat optik"},
         "javob": "A"},
    34: {"savol": "OUQ modulliy sxemada qanday interfeys asosida ishlaydi?",
         "variantlar": {"A": "Compact PCI", "B": "RS-232", "C": "USB", "D": "HDMI"}, "javob": "A"},
    35: {"savol": "Ketma-ket interfeyslarda qaysi protokollar ishlatiladi?",
         "variantlar": {"A": "BOSHLASH, TO‘XTASH, NAZORAT bitlari", "B": "HTTP", "C": "TCP/IP", "D": "UDP"},
         "javob": "A"},
    36: {"savol": "Datchiklar qanday fizik kattaliklarni elektr signallariga o‘zgartiradi?",
         "variantlar": {"A": "Harorat, bosim, namlik", "B": "Rang, yorug‘lik", "C": "Ovoz, tebranish",
                        "D": "Rang, gaz, ultratovush"}, "javob": "A"},
    37: {"savol": "Jamlagich sanoq qurilma (SQ) qaysi qurilmada ishlatiladi?",
         "variantlar": {"A": "ARO‘ qurilmada", "B": "Rele qurilmalarida", "C": "Bajaruvchi qurilmada",
                        "D": "Interfeys adapterlarida"}, "javob": "A"},
    38: {"savol": "RAO‘ qurilma chiqishi qanday qurilmaga ulanadi?",
         "variantlar": {"A": "Bajaruvchi qurilmalar", "B": "ARO‘", "C": "Kommutator", "D": "Interfeys"}, "javob": "A"},
    39: {"savol": "ARO‘ qurilmaning chiqishida qanday qiymat olinadi?",
         "variantlar": {"A": "Raqamli kod", "B": "Analog signal", "C": "Signal chastotasi", "D": "O‘lchash oraliqlari"},
         "javob": "A"},
    40: {"savol": "Signallarni yagona shkalaga keltirish uchun nima ishlatiladi?",
         "variantlar": {"A": "Kuchaytirgichlar va signal filtrlari", "B": "Jamlagichlar", "C": "Demultipleksorlar",
                        "D": "Modemlar"}, "javob": "A"},
    41: {"savol": "O‘rnatilgan tizimlar nima?",
         "variantlar": {"A": "Apparatura va dasturiy ta’minot uyg‘unlashgan tizimlar",
                        "B": "Mustaqil ishlaydigan grafik tizimlar", "C": "Faqat dasturiy ta’minotdan iborat tizimlar",
                        "D": "Kompyuter o‘yin tizimlari"}, "javob": "A"},
    42: {"savol": "Mikrokontroller qanday qurilma hisoblanadi?",
         "variantlar": {"A": "Dasturlanuvchi hisoblash qurilmasi", "B": "Faqat kirish-chiqish qurilmasi",
                        "C": "Faqat axborot saqlovchi qurilma", "D": "Faqat mikroprotsessor"}, "javob": "A"},
    43: {"savol": "Mikroprotsessor tizimidagi asosiy shinalardan biri qaysi?",
         "variantlar": {"A": "Manzil shinasi", "B": "Grafik shinasi", "C": "Tarmoq shinasi", "D": "Tovush shinasi"},
         "javob": "A"},
    44: {"savol": "Intel firmasi tomonidan yaratilgan birinchi mikrokontroller qaysi?",
         "variantlar": {"A": "8048", "B": "8086", "C": "4004", "D": "8080"}, "javob": "A"},
    45: {"savol": "Mikrokontrollerning asosiy tarkibiy qismlariga nimalar kiradi?",
         "variantlar": {"A": "Protsessor, xotira, kirish-chiqish portlari", "B": "Faqat operativ xotira",
                        "C": "Faqat protsessor va video karta", "D": "Faqat elektr manbai"}, "javob": "A"},
    46: {"savol": "DSP qisqartmasi nimani anglatadi?",
         "variantlar": {"A": "Digital Signal Processor", "B": "Digital Sound Processor",
                        "C": "Digital Secure Processor", "D": "Dual Signal Processing"}, "javob": "A"},
    47: {"savol": "Mikrokontroller tizimlarining asosiy afzalligi nima?",
         "variantlar": {"A": "Energiya tejamkorligi", "B": "Murakkab arxitektura", "C": "Yuqori narx",
                        "D": "Faqat grafik ishlov berish"}, "javob": "A"},
    48: {"savol": "Mikroprotsessor tizimida nechta asosiy quyi bosqichli shina mavjud?",
         "variantlar": {"A": "4", "B": "3", "C": "2", "D": "5"}, "javob": "A"},
    49: {"savol": "Pentium Pro protsessorida qanday texnologiya birinchi bor joriy etilgan?",
         "variantlar": {"A": "Dynamic Execution", "B": "HyperThreading", "C": "SSE4", "D": "Vulkan"}, "javob": "A"},
    50: {"savol": "Grafik protsessorlar odatda nima uchun ishlatiladi?",
         "variantlar": {"A": "Vizualizatsiya (grafik tasvirlar)", "B": "Signal uzatish", "C": "Elektr ta’minoti",
                        "D": "Ma’lumotlar saqlash"}, "javob": "A"},
    51: {"savol": "Mikrokontrollerlar qanday arxitektura asosida ishlab chiqiladi?",
         "variantlar": {"A": "Umumiy yoki alohida shinali arxitektura", "B": "Vektorli arxitektura",
                        "C": "Server arxitekturasi", "D": "Parallel arxitektura"}, "javob": "A"},
    52: {"savol": "Intel 4004 protsessorining razryadligi nechaga teng edi?",
         "variantlar": {"A": "4 bit", "B": "8 bit", "C": "16 bit", "D": "32 bit"}, "javob": "A"},
    53: {"savol": "Mikrokontrollerlar ko‘p hollarda qanday qurilmalarda ishlatiladi?",
         "variantlar": {"A": "O‘rnatilgan tizimlarda", "B": "Video montaj stansiyalari", "C": "Superkompyuterlar",
                        "D": "Data markazlarda"}, "javob": "A"},
    54: {"savol": "Mikroprotsessorning razryadligi nima bilan belgilanadi?",
         "variantlar": {"A": "Axborotlar va manzillar shinasining kengligi bilan", "B": "Signal chastotasi bilan",
                        "C": "Yadro soni bilan", "D": "Grafik interfeysi bilan"}, "javob": "A"},
    55: {"savol": "Kristaldagi tizim (SoC) deganda nima tushuniladi?",
         "variantlar": {"A": "Bitta kristalda joylashtirilgan barcha qurilmalar", "B": "Grafik adapterlar majmuasi",
                        "C": "Alohida qurilmalar to‘plami", "D": "Kompyuter qobig‘i"}, "javob": "A"},
    56: {"savol": "Mikroprotsessorli tizimning boshqaruv shinasi nima uchun xizmat qiladi?",
         "variantlar": {"A": "Axborotlar uzatilish vaqti va tartibini boshqarish uchun",
                        "B": "Qurilmalarning manzilini aniqlash", "C": "Axborot uzatish",
                        "D": "Faqat video signal yuborish uchun"}, "javob": "A"},
    57: {"savol": "Mikrokontrollerlar qanday maqsadlar uchun optimallashtirilgan?",
         "variantlar": {"A": "Maxsus vazifalar, energiya tejamkorlik", "B": "Ko‘p foydalanuvchili tizimlar",
                        "C": "Yuqori tezlikdagi serverlar", "D": "O‘yin tizimlari"}, "javob": "A"},
    58: {"savol": "Intel 8080 mikroprotsessorining afzalligi nimada edi?",
         "variantlar": {"A": "64 Kbayt hotiraga manzillash imkoniyati", "B": "Dastur o‘zgartirish imkoni yo‘qligi",
                        "C": "4-bitli ishlov", "D": "Faqat kalkulyatorlar uchun mo‘ljallanganligi"}, "javob": "A"},
    59: {"savol": "Mikrokontrollerlar dasturlarni saqlash uchun qanday hotiradan foydalanadi?",
         "variantlar": {"A": "Doimiy hotira", "B": "Qattiq disk", "C": "Operativ hotira", "D": "USB flesh xotira"},
         "javob": "A"},
    60: {"savol": "Mikroprotsessor tizimining unumdorligi nimaga bog‘liq?",
         "variantlar": {"A": "Takt chastotasi va hotiraga murojaat vaqtiga", "B": "Klaviatura tezligiga",
                        "C": "Elektron ekran hajmiga", "D": "Rangli interfeysga"}, "javob": "A"},
    61: {"savol": "Mikrokontroller protsessorining asosiy vazifasi nima?",
         "variantlar": {"A": "Ma'lumotlarni qayta ishlash va tashqi qurilmalar bilan aloqa",
                        "B": "Buyruqlarni boshqarish", "C": "Grafik ma'lumotlarni chiqarish",
                        "D": "Faqatgina xotirani boshqarish"}, "javob": "A"},
    62: {"savol": "Mikrokontrollerda buyruqlar qanday xotirada saqlanadi?",
         "variantlar": {"A": "Buyruqlar xotirasi", "B": "Kesh xotira", "C": "Operativ xotira", "D": "Registr"},
         "javob": "A"},
    63: {"savol": "Takt generatorining vazifasi nima?",
         "variantlar": {"A": "Signallar ketma-ketligini yaratish", "B": "Xotirani boshqarish", "C": "Manzilni aniqlash",
                        "D": "Axborotni siqish"}, "javob": "A"},
    64: {"savol": "Dastur xotirasining asosiy xususiyati nima?",
         "variantlar": {"A": "Energiya bo‘lmasa ham axborotni saqlay olish", "B": "Tezkorligi",
                        "C": "Energiya iste'mol qilishining yuqoriligi", "D": "Operativ ishlov"}, "javob": "A"},
    65: {"savol": "Axborotlar xotirasida qanday qurilma ishlatiladi?",
         "variantlar": {"A": "Statik OXQ", "B": "Dinamik OXQ", "C": "ROM", "D": "PROM"}, "javob": "A"},
    66: {"savol": "Kesh xotira qanday vazifani bajaradi?",
         "variantlar": {"A": "Protsessor va tizimli xotira o‘rtasidagi tezkor almashuvni ta’minlash",
                        "B": "Faollashtirish", "C": "Faqat saqlash", "D": "Registrlarni boshqarish"}, "javob": "A"},
    67: {"savol": "Ichki kesh xotira nima deb ataladi?",
         "variantlar": {"A": "Birinchi bosqich kesh", "B": "Ikkilamchi kesh", "C": "Kengaytirilgan kesh",
                        "D": "Dinamik kesh"}, "javob": "A"},
    68: {"savol": "Kesh xotiraning \"Tag\" maydoni nima uchun ishlatiladi?",
         "variantlar": {"A": "Manzilni aniqlash", "B": "Axborot blokini saqlash", "C": "Haqiqiyligini belgilash",
                        "D": "Kesh hajmini hisoblash"}, "javob": "A"},
    69: {"savol": "Buyruqlar tizimi qanday guruhlarga ajratiladi?",
         "variantlar": {"A": "4", "B": "2", "C": "3", "D": "5"}, "javob": "A"},
    70: {"savol": "Kesh xotiraning kogorentligini saqlash nima uchun zarur?",
         "variantlar": {"A": "Axborotning bir xilda bo‘lishini ta’minlash", "B": "Sinxronizatsiyani buzish",
                        "C": "Xatoliklarni oldini olish", "D": "Ishlash tezligini pasaytirish"}, "javob": "A"},
    71: {"savol": "Mikrokontrollerda buyruqlar qanday manzillash usullari bilan aniqlanadi?",
         "variantlar": {"A": "Turli manzillash usullari bilan", "B": "Statik va dinamik", "C": "Virtual va fizik",
                        "D": "Faqatgina fizik"}, "javob": "A"},
    72: {"savol": "Kesh xotiraning \"Valid\" maydoni nimani bildiradi?",
         "variantlar": {"A": "Haqiqiylik holatini", "B": "Ma’lumotlar hajmini", "C": "Operatsiya kodini",
                        "D": "Manzilni"}, "javob": "A"},
    73: {"savol": "Kesh xotiraning uchinchi bosqichi qaysi qurilmaga asoslanadi?",
         "variantlar": {"A": "Statik OXQ", "B": "Registr", "C": "Dinamik OXQ", "D": "Doimiy xotira"}, "javob": "A"},
    74: {"savol": "Mikrokontrollerda qanday xotira turlari mavjud?",
         "variantlar": {"A": "Dastur va axborotlar xotirasi", "B": "Registr va RAM", "C": "Statik va dinamik",
                        "D": "ROM va PROM"}, "javob": "A"},
    75: {"savol": "Registrlarning vazifasi nima?",
         "variantlar": {"A": "Tizim resurslarini boshqarish", "B": "Signalni boshqarish", "C": "Grafikni chiqarish",
                        "D": "Operativ xotirani boshqarish"}, "javob": "A"},
    76: {"savol": "DXQ qanday turga bo‘linadi?",
         "variantlar": {"A": "Bir marta va ko‘p marta dasturlanuvchi", "B": "Yozilmaydigan va o‘chirilmaydigan",
                        "C": "Ko‘chiriladigan va ko‘chirib bo‘lmaydigan", "D": "Statik va dinamik"}, "javob": "A"},
    77: {"savol": "Axborotlar xotirasining sig‘imi odatda qanday?",
         "variantlar": {"A": "O‘nlab va yuzlab baytlarda", "B": "Megabaytlarda", "C": "Gigabaytlarda",
                        "D": "Terabaytlarda"}, "javob": "A"},
    78: {"savol": "Mikrokontroller protsessorining asosiy sxemasi nimani o‘z ichiga oladi?",
         "variantlar": {"A": "Takt generatori, shina kontrolleri va boshqalar", "B": "Protsessor yadrosi va registrlar",
                        "C": "RAM va ROM", "D": "Kesh va tashqi qurilmalar"}, "javob": "A"},
    79: {"savol": "Kesh xotiraning asosiy maqsadi nima?",
         "variantlar": {"A": "Tezkor axborotga ega bo‘lish", "B": "Saqlash joyini oshirish",
                        "C": "Protsessorni o‘chirib qo‘yish", "D": "Tizimni sekinlashtirish"}, "javob": "A"},
    80: {"savol": "Kesh xotira bilan ishlaganda axborot necha joyda bo‘lishi mumkin?",
         "variantlar": {"A": "Ikkita joyda", "B": "Uchta joyda", "C": "Faqat bitta joyda", "D": "Har xil joylarda"},
         "javob": "A"},
    81: {"savol": "DSP qisqartmasi nimani anglatadi?",
         "variantlar": {"A": "Digital Signal Processor", "B": "Dynamic Signal Processor",
                        "C": "Digital Speed Processor", "D": "Direct Speed Processor"}, "javob": "A"},
    82: {"savol": "Signallarga ishlov berish protsessorlari qanday xususiyatga ega?",
         "variantlar": {"A": "Real vaqt rejimida ishlov berish", "B": "Past quvvat sarfi", "C": "Sekin ishlov berish",
                        "D": "Faqat analog signallarni qabul qilish"}, "javob": "A"},
    83: {"savol": "Akkumulator qanday qurilma?",
         "variantlar": {"A": "Oraliq natijalarni saqlovchi registr", "B": "Doimiy xotira", "C": "Axborotlar bazasi",
                        "D": "Vektorli ko‘paytiruvchi"}, "javob": "A"},
    84: {"savol": "Konveyerli ishlov berishning asosiy afzalligi nima?",
         "variantlar": {"A": "O‘tkazuvchanlikni oshiradi", "B": "Parallel ishlov mumkin emas",
                        "C": "Buyruqlarni ketma-ketlikda bajaradi", "D": "Narxi arzon"}, "javob": "A"},
    85: {"savol": "Katta uzunlikdagi buyruq so‘zlari texnologiyasi qanday qisqartma bilan belgilanadi?",
         "variantlar": {"A": "VLIW", "B": "VLSI", "C": "VDSP", "D": "VLSP"}, "javob": "A"},
    86: {"savol": "VLIW protsessorida bir vaqtda buyruqlar qanday bajariladi?",
         "variantlar": {"A": "Turli funksional bloklarda", "B": "Bitta registrda", "C": "Faqat bitta ALU orqali",
                        "D": "Takt generatorida"}, "javob": "A"},
    87: {"savol": "Signal protsessorida operandani surish qanday amalga oshiriladi?",
         "variantlar": {"A": "Maxsus apparatli qurilma orqali", "B": "Albatta ALU orqali", "C": "Faqat dasturiy usulda",
                        "D": "Faqat chapga suriladi"}, "javob": "A"},
    88: {"savol": "Ko‘p yadroli protsessorlar nima imkon beradi?",
         "variantlar": {"A": "Parallel ishlov va samaradorlik", "B": "Yagona oqimda ishlov",
                        "C": "Past energiya iste’molini", "D": "Faqat DSP signallarini qayta ishlash"}, "javob": "A"},
    89: {"savol": "SMR qisqartmasi nimani bildiradi?",
         "variantlar": {"A": "Single Mode Register", "B": "Signal Management Routine", "C": "Chip Multiprocessing",
                        "D": "Small Memory Range"}, "javob": "A"},
    90: {"savol": "ARM protsessorlari ko‘proq qayerda qo‘llaniladi?",
         "variantlar": {"A": "Mobil va o‘rnatilgan tizimlarda", "B": "Faqat serverlarda", "C": "Superkompyuterlarda",
                        "D": "Faqat audio uskunalarda"}, "javob": "A"},
    91: {"savol": "ARM Cortex-A5 modeli qanday xususiyatga ega?",
         "variantlar": {"A": "Kam energiya iste’mol qiluvchi protsessor", "B": "Faqat bitta ALUga ega",
                        "C": "Eng katta quvvat sarfi", "D": "Raqamli kameralarda ishlatiladi"}, "javob": "A"},
    92: {"savol": "VLIW kompilyatori nima qiladi?",
         "variantlar": {"A": "Parallel bajariladigan buyruqlarni topadi", "B": "Buyruqlarni muvofiqlashtiradi",
                        "C": "Buyruqlarni ketma-ketlikda beradi", "D": "Protsessor chastotasini oshiradi"},
         "javob": "A"},
    93: {"savol": "VLIW paketining uzunligi necha bit?",
         "variantlar": {"A": "256 bit", "B": "128 bit", "C": "64 bit", "D": "512 bit"}, "javob": "A"},
    94: {"savol": "Surish bloklari VLIW protsessorida qanday belgilanadi?",
         "variantlar": {"A": "S1, S2", "B": "D1, D2", "C": "L1, L2", "D": "A1, A2"}, "javob": "A"},
    95: {"savol": "M1 va M2 bloklarining vazifasi nima?",
         "variantlar": {"A": "Ko‘paytirish amallarini bajarish", "B": "Mantiqiy amallar bajarish",
                        "C": "Axborotni saqlash", "D": "Takt chastotasini boshqarish"}, "javob": "A"},
    96: {"savol": "ARM 11 mikroarxitekturasi nechta protsessorgacha qo‘llab-quvvatlaydi?",
         "variantlar": {"A": "1–4", "B": "2–3", "C": "1–2", "D": "4–8"}, "javob": "A"},
    97: {"savol": "Ko‘p yadroli tizimlarda dasturiy oqim nima?",
         "variantlar": {"A": "Mustaqil buyruqlar ketma-ketligi", "B": "Faqat kompilyator buyruqlari",
                        "C": "Faqat registrlar ketma-ketligi", "D": "Takt generatoridan hosil bo‘lgan oqim"},
         "javob": "A"},
    98: {"savol": "ARM protsessoridagi NEON moduli nima uchun ishlatiladi?",
         "variantlar": {"A": "Suriluvchi vergulli hisob-kitoblar uchun", "B": "Keshni boshqarish uchun",
                        "C": "Operativ xotira uchun", "D": "Tarmoqni boshqarish uchun"}, "javob": "A"},
    99: {"savol": "ARM Cortex-A5 protsessorining chastotasi necha MGs?",
         "variantlar": {"A": "1000 MGs", "B": "680 MGs", "C": "480 MGs", "D": "120 MGs"}, "javob": "A"},
    100: {"savol": "ARM Cortex-A5 protsessorida kesh xotiraning sig‘imi qanday?",
          "variantlar": {"A": "16/16 Kbayt", "B": "4/4 Kbayt", "C": "8/8 Kbayt", "D": "32/32 Kbayt"}, "javob": "A"},
    101: {"savol": "Taymerning asosiy vazifasi nima?",
          "variantlar": {"A": "Vaqt oralig‘ini hisoblash", "B": "Signallarni uzatish", "C": "Keshni boshqarish",
                         "D": "Fayllarni saqlash"}, "javob": "A"},
    102: {"savol": "Qo‘riqchi taymer nima uchun ishlatiladi?",
          "variantlar": {"A": "Tizimning ishlashini himoyalash uchun",
                         "B": "Tizimda uzilish sodir bo‘lishini aniqlash uchun",
                         "C": "Operativ xotirani kengaytirish uchun", "D": "Disklar bilan ishlash uchun"},
          "javob": "A"},
    103: {"savol": "Real vaqt tizimlarida uzilishlarga kechikish nima keltirib chiqaradi?",
          "variantlar": {"A": "Salbiy oqibatlar", "B": "Tez ishlash", "C": "Past energiya iste’moli",
                         "D": "Yuqori sifat"}, "javob": "A"},
    104: {"savol": "Taymer qanday qurilmaga asoslanadi?",
          "variantlar": {"A": "Ikkilik sanoq qurilmasi", "B": "Dinamik hotira", "C": "Protsessor yadrosi",
                         "D": "Registrlar majmuasi"}, "javob": "A"},
    105: {"savol": "Tizimni sinxronlashtirish uchun qanday qurilma ishlatiladi?",
          "variantlar": {"A": "Taymer", "B": "Monitor", "C": "Disk", "D": "Printer"}, "javob": "A"},
    106: {"savol": "Uzilish tizimida qanday ustuvorlik aniqlanadi?",
          "variantlar": {"A": "Uzilishlar orasida muhimlik darajasi", "B": "Buyruq soni", "C": "Tizim yuklanishi",
                         "D": "Dastur uzunligi"}, "javob": "A"},
    107: {"savol": "Uzilishlar kontrolleri shaxsiy kompyuterlarda qanday nomlanadi?",
          "variantlar": {"A": "PIC", "B": "CPU", "C": "ALU", "D": "RAM"}, "javob": "A"},
    108: {"savol": "Uzilishni qanday holat sifatida talqin qilish mumkin?",
          "variantlar": {"A": "Dasturning to‘xtab, boshqa holatga o‘tishi", "B": "Buyruq bajarilishining davomiyligi",
                         "C": "Xotira to‘lishi", "D": "Xatoliklarni avtomatik tuzatish"}, "javob": "A"},
    109: {"savol": "Uzilishga ishlov beruvchi dastur qanday nomlanadi?",
          "variantlar": {"A": "Interrupt handler", "B": "Taymer", "C": "Kernel", "D": "BIOS"}, "javob": "A"},
    110: {"savol": "Stek qanday hotira turi?", "variantlar": {"A": "LIFO", "B": "FIFO", "C": "ROM", "D": "DRAM"},
          "javob": "A"},
    111: {"savol": "Dasturiy uzilishlar qanday yuzaga keladi?",
          "variantlar": {"A": "Dasturning ichida sinxron ravishda", "B": "Signal generatori orqali",
                         "C": "Operatsion tizim buyrug‘i bilan", "D": "Kesh xotirasi orqali"}, "javob": "A"},
    112: {"savol": "INT buyrug‘i odatda nima uchun ishlatiladi?",
          "variantlar": {"A": "Operatsion tizim funksiyasini chaqirish uchun", "B": "Tizimni o‘chirib qo‘yish uchun",
                         "C": "Faqatgina ekran bilan ishlash uchun", "D": "Diskni formatlash uchun"}, "javob": "A"},
    113: {"savol": "Uzilishlar kontrollerining vazifasi nima?",
          "variantlar": {"A": "Uzilishlarni boshqarish va ustuvorlikni aniqlash", "B": "Operativ xotirani tozalash",
                         "C": "Buyruqlarni tezlashtirish", "D": "Fayllarni uzatish"}, "javob": "A"},
    114: {"savol": "Uzilishlar qaysi usulda yuzaga keladi?",
          "variantlar": {"A": "Dasturiy va apparatli", "B": "Faqat disk orqali", "C": "Faqat tarmoq orqali",
                         "D": "Faqat analog qurilmalar orqali"}, "javob": "A"},
    115: {"savol": "Stack operativ xotirada qanday ishlaydi?",
          "variantlar": {"A": "Oxirgi kiritilgan ma’lumot birinchi chiqadi",
                         "B": "Barcha ma’lumotlar ketma-ket saqlanadi", "C": "Ma’lumotlar qayta yoziladi",
                         "D": "Faqat raqamli signal saqlaydi"}, "javob": "A"},
    116: {"savol": "Uzilish vektor jadvali nima?",
          "variantlar": {"A": "Uzilishga ishlov beruvchi manzillar ro‘yxati", "B": "Registrlar ro‘yxati",
                         "C": "BIOS sozlamalari ro‘yxati", "D": "Kesh adreslari"}, "javob": "A"},
    117: {"savol": "Qo‘riqchi taymer nima bilan bog‘liq?",
          "variantlar": {"A": "Buzilish holatlarini aniqlash bilan", "B": "Monitor bilan",
                         "C": "Tarmoq interfeysi bilan", "D": "Faqat signal kuchaytirish bilan"}, "javob": "A"},
    118: {"savol": "Taymerda nolga yetganda nima sodir bo‘ladi?",
          "variantlar": {"A": "Signal beriladi", "B": "Qurilma o‘chadi", "C": "Dasturni o‘chiradi",
                         "D": "Tizimni qayta yuklaydi"}, "javob": "A"},
    119: {"savol": "Tashqi qurilmalardan kelgan uzilishlar qanday ko‘rinishda bo‘ladi?",
          "variantlar": {"A": "Signal shaklida", "B": "Analog ma’lumotlar oqimi", "C": "Faqat audio signal",
                         "D": "Grafik shaklida"}, "javob": "A"},
    120: {"savol": "Uzilishga ishlov berish vaqtida yangi uzilish kelganda nima bo‘ladi?",
          "variantlar": {"A": "Yangi uzilish ham joylashtiriladi", "B": "Avvalgi uzilish bekor qilinadi",
                         "C": "Yangi uzilish keyin bajariladi", "D": "Yangi uzilish e’tiborga olinmaydi"},
          "javob": "A"},
    121: {"savol": "Analog signallar qanday xususiyatga ega?",
          "variantlar": {"A": "Uzluksiz va har qanday qiymatga ega bo‘lishi mumkin", "B": "Diskret xarakterga ega",
                         "C": "Faqat ikkita qiymatga ega", "D": "Faqat raqamli tizimlarda ishlatiladi"}, "javob": "A"},
    122: {"savol": "Raqamli signallar qanday ko‘rinishga ega?",
          "variantlar": {"A": "Diskret", "B": "Fazoviy", "C": "Analog", "D": "Uzluksiz"}, "javob": "A"},
    123: {"savol": "Signallarni qayta ishlashdagi asosiy maqsad nima?",
          "variantlar": {"A": "Foydali ma’lumotni ajratish", "B": "Qurilmalarni sozlash", "C": "Fayllarni uzatish",
                         "D": "Energiya tejash"}, "javob": "A"},
    124: {"savol": "Analog signallarni qayta ishlash qanday qurilmalar orqali amalga oshiriladi?",
          "variantlar": {"A": "Elektron sxemalar (filtr, kuchaytirgich)", "B": "Sensorlar", "C": "Protsessorlar",
                         "D": "Operatsion tizimlar"}, "javob": "A"},
    125: {"savol": "Raqamli signallarni qayta ishlash usuliga misol toping:",
          "variantlar": {"A": "Fourier transformatsiyasi", "B": "Yozuv", "C": "Signal kuchaytirish",
                         "D": "Kabel ulash"}, "javob": "A"},
    126: {"savol": "Raqamli signal qanday raqamlardan iborat?",
          "variantlar": {"A": "Faqat 0 va 1", "B": "1–10 oralig‘idagi sonlar", "C": "Har qanday kasr sonlar",
                         "D": "Analog signal ifodasi"}, "javob": "A"},
    127: {"savol": "Signalni sinxronlashtirish nima uchun kerak?",
          "variantlar": {"A": "Signal vaqtini moslashtirish uchun", "B": "Signalni kuchaytirish uchun",
                         "C": "Signalni saqlash uchun", "D": "Signalni siqish uchun"}, "javob": "A"},
    128: {"savol": "Fourier transformatsiyasi yordamida nima amalga oshiriladi?",
          "variantlar": {"A": "Signal chastota spektrini tahlil qilish", "B": "Signalni qisqartirish",
                         "C": "Signalni kuchaytirish", "D": "Signalni shifrli qilish"}, "javob": "A"},
    129: {"savol": "DSP qisqartmasi nimani anglatadi?",
          "variantlar": {"A": "Digital System Program", "B": "Digital Signal Processor", "C": "Data Signal Protocol",
                         "D": "Dynamic Sensor Processing"}, "javob": "A"},
    130: {"savol": "Xususiyatlarga ajratish jarayonining maqsadi nima?",
          "variantlar": {"A": "Foydali belgilarni ajratib olish", "B": "Signalni siqish",
                         "C": "Signalni analogga o‘zgartirish", "D": "Kodlash"}, "javob": "A"},
    131: {"savol": "Chastotaviy tahlilda signal qanday o‘rganiladi?",
          "variantlar": {"A": "Spektral komponentlar bo‘yicha", "B": "Vaqt bo‘yicha", "C": "Vizual grafikda",
                         "D": "Ovoz balandligi orqali"}, "javob": "A"},
    132: {"savol": "Statistik tahlilda quyidagi ko‘rsatkichlardan qaysi biri ishlatiladi?",
          "variantlar": {"A": "O‘rtacha qiymat va dispersiya", "B": "Ekran o‘lchami", "C": "Signal manbai",
                         "D": "Format kodi"}, "javob": "A"},
    133: {"savol": "Deep Feature Learning deganda nima tushuniladi?",
          "variantlar": {"A": "Sun’iy intellektda chuqur o‘rganish orqali xususiyatlarni aniqlash",
                         "B": "Oddiy filtrlash", "C": "Protsessor chastotasini oshirish",
                         "D": "Signalni kompress qilish"}, "javob": "A"},
    134: {"savol": "IoT tizimlarida signal uzatish qanday bo‘ladi?",
          "variantlar": {"A": "Simli va simsiz real vaqt rejimida", "B": "Faqat audio orqali",
                         "C": "Faqat kabellar orqali", "D": "Faqat lokal tarmoq orqali"}, "javob": "A"},
    135: {"savol": "Tibbiy monitoring tizimlarida qanday signallar uzatiladi?",
          "variantlar": {"A": "Yurak urishi, qon bosimi", "B": "Rasm", "C": "GPS koordinatalari",
                         "D": "Dastur kodlari"}, "javob": "A"},
    136: {"savol": "Raqamli signallarni siqish nima uchun kerak?",
          "variantlar": {"A": "Kamroq xotira band qilish uchun", "B": "Sifatni kamaytirish uchun",
                         "C": "Chastotani pasaytirish uchun", "D": "Signalni kuchaytirish uchun"}, "javob": "A"},
    137: {"savol": "Raqamli filtrlarning analog filtrdan farqi nimada?",
          "variantlar": {"A": "Algoritmlar orqali ishlaydi", "B": "Haroratni o‘lchaydi",
                         "C": "Faqat tovushlar uchun ishlatiladi", "D": "Ularni sozlash imkoni yo‘q"}, "javob": "A"},
    138: {"savol": "Sun’iy intellekt signalni qanday qayta ishlaydi?",
          "variantlar": {"A": "Belgilarni o‘rganadi va tahlil qiladi", "B": "Faqat signal uzatadi",
                         "C": "Signalni yo‘q qiladi", "D": "Faqat ekran bilan ishlaydi"}, "javob": "A"},
    139: {"savol": "Biosignallarni qayta ishlash qaysi sohalarda qo‘llaniladi?",
          "variantlar": {"A": "Tibbiyot, sport, xavfsizlik tizimlarida", "B": "Faqat sanoatda",
                         "C": "Faqat televideniyada", "D": "Faqat Internetda"}, "javob": "A"},
    140: {"savol": "Signallarni spektral tahlil qilish qaysi holatda foydali?",
          "variantlar": {"A": "Signal chastotasini o‘rganishda", "B": "Signalni raqamlashtirishda",
                         "C": "Signalni faqat yozishda", "D": "Signalni uzatish uchun"}, "javob": "A"},
    141: {"savol": "DMA qisqartmasi nimani anglatadi?",
          "variantlar": {"A": "Direct Memory Access", "B": "Digital Memory Allocation", "C": "Data Mode Address",
                         "D": "Direct Machine Adapter"}, "javob": "A"},
    142: {"savol": "DMA texnologiyasining asosiy afzalligi nima?",
          "variantlar": {"A": "Protsessor yuklamasini kamaytiradi", "B": "RAM hajmini oshiradi",
                         "C": "Video kartani tezlashtiradi", "D": "Signalni filtrlashni ta’minlaydi"}, "javob": "A"},
    143: {"savol": "DMA kontrolleri nima vazifani bajaradi?",
          "variantlar": {"A": "Ma’lumotlarni xotira va tashqi qurilmalar o‘rtasida uzatadi",
                         "B": "Operatsion tizimni yuklaydi", "C": "Tashqi qurilmani boshqaradi",
                         "D": "Faqat protsessorni boshqaradi"}, "javob": "A"},
    144: {"savol": "DMA qanday ishlaydi?",
          "variantlar": {"A": "Mustaqil holda, protsessor aralashuvisiz", "B": "Operativ xotirani zaxiralaydi",
                         "C": "Protsessor ishtirokida", "D": "Faqat grafik kartalarda"}, "javob": "A"},
    145: {"savol": "DMA orqali ma’lumot uzatishning yo‘nalishlari:",
          "variantlar": {"A": "O‘qish va yozish", "B": "Faqat o‘qish", "C": "Faqat yozish",
                         "D": "Faqat protsessordan tashqi qurilmaga"}, "javob": "A"},
    146: {"savol": "DMA protsessor bilan qanday ishlaydi?",
          "variantlar": {"A": "Sinxron holda va shinalarni almashib ishlatadi", "B": "To‘liq mustaqil",
                         "C": "Protsessor faqat nazorat qiladi", "D": "Hech qanday aloqasi yo‘q"}, "javob": "A"},
    147: {"savol": "DMA kontrolleri nechta asosiy parametr orqali sozlanadi?",
          "variantlar": {"A": "4", "B": "3", "C": "2", "D": "5"}, "javob": "A"},
    148: {"savol": "DMA kontrolleriga uzatiladigan parametrlar tarkibiga nimalar kiradi?",
          "variantlar": {"A": "O‘qish/yozish turi, manzillar va blok hajmi", "B": "Operatsion tizim vaqti",
                         "C": "Protsessor holati", "D": "Ekran sozlamalari"}, "javob": "A"},
    149: {"savol": "DMA uzatishni qanday boshlaydi?",
          "variantlar": {"A": "Protsessor tomonidan ishga tushiriladi", "B": "Foydalanuvchi tomonidan",
                         "C": "Avtomatik", "D": "Elektr signal orqali"}, "javob": "A"},
    150: {"savol": "DMA texnologiyasi qaysi qurilmalarda keng qo‘llaniladi?",
          "variantlar": {"A": "Tashqi qurilmalar: disklar, tarmoq adapterlari", "B": "Faqat printerlarda",
                         "C": "Faqat mobil telefonlarda", "D": "Faqat RAM modullarda"}, "javob": "A"},
    151: {"savol": "DMA kontrolleri ishga tushganda protsessor nima qiladi?",
          "variantlar": {"A": "O‘z faoliyatini davom ettiradi", "B": "Ishlashni to‘xtatadi", "C": "Kutib turadi",
                         "D": "Faqat kuzatadi"}, "javob": "A"},
    152: {"savol": "DMA va protsessor o‘rtasidagi uzatish qanday resursdan foydalanadi?",
          "variantlar": {"A": "Tizimli shinalar", "B": "Operatsion tizim buferi", "C": "Kesh xotira",
                         "D": "Displey buferi"}, "javob": "A"},
    153: {"savol": "DMA yordamida ma’lumot uzatishning unumdorligi qanday oshiriladi?",
          "variantlar": {"A": "Parallel uzatish orqali", "B": "Tizimni qayta yuklash orqali",
                         "C": "RAMni tozalash orqali", "D": "Sozlamalarni o‘zgartirish orqali"}, "javob": "A"},
    154: {"savol": "DMA texnologiyasi protsessorga qanday foyda keltiradi?",
          "variantlar": {"A": "Resurslarni asosiy hisoblashga yo‘naltiradi", "B": "Grafik ishlovga e’tibor qaratadi",
                         "C": "Ishlash chastotasini oshiradi", "D": "Diskni tezlik bilan formatlaydi"}, "javob": "A"},
    155: {"savol": "DMA o‘z ishini qanday asosda bajaradi?",
          "variantlar": {"A": "Protsessor ko‘rsatmasidan so‘ng", "B": "O‘z-o‘zidan", "C": "Ketma-ketlikda",
                         "D": "Diskdan signal olganda"}, "javob": "A"},
    156: {"savol": "DMA texnologiyasining asosiy vazifasi nima?",
          "variantlar": {"A": "Ma’lumot almashinuvida protsessor aralashuvini kamaytirish",
                         "B": "Ovozli signal uzatish", "C": "Xotirani formatlash", "D": "Tizim dasturlarini yuklash"},
          "javob": "A"},
    157: {"savol": "DMA kontrolleri qayerga o‘rnatiladi?",
          "variantlar": {"A": "Protsessor kristali ichida yoki yonida", "B": "Albatta alohida chipda",
                         "C": "Disk ichida", "D": "Operatsion tizimda"}, "javob": "A"},
    158: {"savol": "DMA orqali ma’lumot uzatilayotgan blok qanday ko‘rsatiladi?",
          "variantlar": {"A": "Xotira manzili va blok o‘lchami bilan", "B": "O‘chirish kodi bilan",
                         "C": "Signal raqami bilan", "D": "Tizim buferi orqali"}, "javob": "A"},
    159: {"savol": "DMAdan foydalanganda protsessor yuklamasi qanday o‘zgaradi?",
          "variantlar": {"A": "Kamayadi", "B": "O‘zgarmaydi", "C": "Ortadi", "D": "Butunlay yo‘qoladi"}, "javob": "A"},
    160: {"savol": "DMA texnologiyasining amaliy qo‘llanilish sohasi:",
          "variantlar": {"A": "Tashqi qurilma bilan real vaqt uzatmalar", "B": "Avtomobil dvigatellari",
                         "C": "Faqat ofis dasturlarida", "D": "Monitor sozlamalarida"}, "javob": "A"},
    161: {"savol": "Kiritish/chiqarish kontrollerining asosiy vazifasi nima?",
          "variantlar": {"A": "Qurilmalar orasida signal almashinuvi", "B": "Operativ xotirani nazorat qilish",
                         "C": "Faqat protsessorni boshqarish", "D": "Printerlarni sozlash"}, "javob": "A"},
    162: {"savol": "USB interfeysining asosiy vazifasi nima?",
          "variantlar": {"A": "Tashqi qurilmalarni ulash", "B": "Internetga ulanish", "C": "Video tahrirlash",
                         "D": "Operatsion tizimni o‘rnatish"}, "javob": "A"},
    163: {"savol": "PCI interfeysi nima uchun ishlatiladi?",
          "variantlar": {"A": "Ichki apparat komponentlarini ulash", "B": "Internet tarmog‘iga ulanish",
                         "C": "Printer ulash", "D": "RAM o‘rnatish"}, "javob": "A"},
    164: {"savol": "RS-485 interfeysi qanday vazifani bajaradi?",
          "variantlar": {"A": "Uzoq masofaga ma’lumot uzatadi", "B": "Video tarmoqni boshqaradi",
                         "C": "Kamera sozlamalarini yangilaydi", "D": "Boshqarish paneli interfeysi"}, "javob": "A"},
    165: {"savol": "SPI interfeysining ishlash prinsipi qanday?",
          "variantlar": {"A": "Master-slave asosida", "B": "Klaviatura orqali boshqarish",
                         "C": "Har bir qurilmaga alohida IP beriladi", "D": "Bluetooth orqali uzatiladi"},
          "javob": "A"},
    166: {"savol": "I2C interfeysi qanday manzillashdan foydalanadi?",
          "variantlar": {"A": "7 yoki 10-bit", "B": "16-bit", "C": "4-bit", "D": "64-bit"}, "javob": "A"},
    167: {"savol": "UART interfeysi qanday uzatish turiga kiradi?",
          "variantlar": {"A": "Asinxron", "B": "Sinxron", "C": "Ko‘p pog‘onali", "D": "Faqat kirish"}, "javob": "A"},
    168: {"savol": "Ketma-ket uzatish qanday turga ega emas?",
          "variantlar": {"A": "Parallels", "B": "Yarim-dupleks", "C": "Dupleks", "D": "Simpleks"}, "javob": "A"},
    169: {"savol": "Ethernet interfeysi qaysi protokol asosida ishlaydi?",
          "variantlar": {"A": "TCP/IP", "B": "FTP", "C": "UDP", "D": "DNS"}, "javob": "A"},
    170: {"savol": "Apparat interfeysi nima uchun kerak?",
          "variantlar": {"A": "Ma’lumotni fizik jihatdan uzatish", "B": "Qurilmalarni bo‘yash",
                         "C": "Elektr toki o‘tkazish", "D": "Ma’lumotlarni siqish"}, "javob": "A"},
    171: {"savol": "Ketma-ket uzatishda ma’lumot qanday tartibda uzatiladi?",
          "variantlar": {"A": "Bir bitdan", "B": "Bosqichma-bosqich", "C": "Birdaniga", "D": "Parallel"}, "javob": "A"},
    172: {"savol": "LIN interfeysi qayerda keng qo‘llaniladi?",
          "variantlar": {"A": "Avtomobillar tarmog‘ida", "B": "Uy tarmog‘ida", "C": "GPS qurilmalarida",
                         "D": "Ofis printerlarida"}, "javob": "A"},
    173: {"savol": "M2M texnologiyasi nima uchun ishlatiladi?",
          "variantlar": {"A": "Qurilmalararo avtomatik aloqa", "B": "Kompyuter grafikasi uchun",
                         "C": "Faqat sanoat dvigatellari uchun", "D": "Xavfsizlik signalizatsiyasi"}, "javob": "A"},
    174: {"savol": "SoC tizimlar qaysi interfeyslarga muxtoj bo‘ladi?",
          "variantlar": {"A": "Qo‘shimcha maxsuslashtirilgan interfeyslar", "B": "Faqat USB",
                         "C": "Internet interfeysi", "D": "HDMI"}, "javob": "A"},
    175: {"savol": "RS-232C interfeysi qanday qurilmalar bilan ishlaydi?",
          "variantlar": {"A": "Real vaqt soatlari va EEPROM xotira", "B": "Skanerlar", "C": "USB fleshkalar",
                         "D": "Kamera sensorlari"}, "javob": "A"},
    176: {"savol": "SPI interfeysining asosiy vazifasi nima?",
          "variantlar": {"A": "Raqamli potensiometrlar bilan ishlash", "B": "Klaviatura signalini uzatish",
                         "C": "Video fayllarni siqish", "D": "Printerlarni sozlash"}, "javob": "A"},
    177: {"savol": "Protsessor va portlar orasidagi axborot qanday almashiladi?",
          "variantlar": {"A": "Dasturiy-boshqaruv yo‘li bilan", "B": "Parol orqali", "C": "Telefon orqali",
                         "D": "Dasturiy kompilyatsiya"}, "javob": "A"},
    178: {"savol": "Asinxron uzatish nima?",
          "variantlar": {"A": "Doimiy bo‘lmagan vaqt oraliqlarda uzatish", "B": "Har doim bir xil tezlikda uzatish",
                         "C": "Har bir baytdan keyin pauza", "D": "Faqat lokal tarmoqlarda qo‘llaniladi"},
          "javob": "A"},
    179: {"savol": "CW va SW axborotlar turi nimani anglatadi?",
          "variantlar": {"A": "Boshqarish signallari", "B": "Video axborotlar", "C": "Sensor ma’lumotlari",
                         "D": "RAM axborotlari"}, "javob": "A"},
    180: {"savol": "TWI interfeysi qaysi interfeys bilan tenglashtiriladi?",
          "variantlar": {"A": "I2C", "B": "SPI", "C": "UART", "D": "USB"}, "javob": "A"},
    181: {"savol": "Operatsion tizim (OT) qanday rol o‘ynaydi?",
          "variantlar": {"A": "Foydalanuvchi dasturlari va apparat orasida vositachi bo‘ladi",
                         "B": "Protsessorni nazorat qiladi", "C": "Faqat drayverlarni o‘rnatadi",
                         "D": "Faqat Internet bilan ishlaydi"}, "javob": "A"},
    182: {"savol": "Real vaqt operatsion tizimining (RV OT) asosiy talabi nima?",
          "variantlar": {"A": "O‘z vaqtida ishlov berish", "B": "Tez yuklanish", "C": "Arzon narx",
                         "D": "Ko‘p funksiyalilik"}, "javob": "A"},
    183: {"savol": "Monolit arxitekturali OTda foydalanuvchi rejimi qanday huquqlarga ega?",
          "variantlar": {"A": "Cheklangan huquqlar", "B": "Tarmoqni boshqarish", "C": "To‘liq tizimga kirish",
                         "D": "Ilovalarni tahrirlash"}, "javob": "A"},
    184: {"savol": "Protsessor tizim chaqirig‘ida nima qiladi?",
          "variantlar": {"A": "Foydalanuvchi rejimidan yadro rejimiga o‘tadi", "B": "Tarmoqga ulanadi",
                         "C": "Kompyuterni o‘chiradi", "D": "USB drayverni o‘rnatadi"}, "javob": "A"},
    185: {"savol": "Modulliy arxitektura qanday tuzilishga asoslanadi?",
          "variantlar": {"A": "Qatlamli modul tizimiga", "B": "Monolit yadroga", "C": "Faqat fayl tizimiga",
                         "D": "Grafik interfeysga"}, "javob": "A"},
    186: {"savol": "Qaysi qatlam boshqa qatlamni chaqira olmaydi?",
          "variantlar": {"A": "Yuqoridagi qatlam faqat pastdagini", "B": "Tizim yadro faqat o‘zini",
                         "C": "Har qanday qatlam har birini", "D": "Yuqoridagi qatlamlar pastdagini"}, "javob": "A"},
    187: {"savol": "Modulliy arxitekturaning afzalliklaridan biri nima?",
          "variantlar": {"A": "Qismlarga bo‘lib sozlash oson", "B": "Monolit tizimdan yengil",
                         "C": "Yadroga to‘g‘ridan-to‘g‘ri aralashish", "D": "Server ishlatmaydi"}, "javob": "A"},
    188: {"savol": "Qatlamli arxitekturadagi foydalanuvchi jarayonlari qanday ishlaydi?",
          "variantlar": {"A": "Ajratilgan va cheklangan kirish bilan", "B": "Barcha tizimga kirish bilan",
                         "C": "Yadro rejimida", "D": "Faoliyatini yadro bilan birga yuritadi"}, "javob": "A"},
    189: {"savol": "“Mijoz-server” arxitekturasi nima asosida ishlaydi?",
          "variantlar": {"A": "Jarayonlararo servis almashinuvi", "B": "Modul ichidagi bog‘lanish",
                         "C": "Fayl uzatish mexiznizmi", "D": "Faqat ilovalararo bog‘lanish"}, "javob": "A"},
    190: {"savol": "Mikroyadro qanday rol o‘ynaydi?",
          "variantlar": {"A": "Jarayonlar boshqaruvini serverga uzatadi", "B": "Ilovalarning fayllarini yaratadi",
                         "C": "Faqat USB ulashni boshqaradi", "D": "Operatsion tizimni yuklaydi"}, "javob": "A"},
    191: {"savol": "Mijoz-server arxitekturasining afzalligi nimada?",
          "variantlar": {"A": "Bitta server ishdan chiqsa ham, tizim ishlayveradi", "B": "Modulda ishlash",
                         "C": "Tizimga to‘g‘ridan-to‘g‘ri kirish", "D": "Yadroda barcha xizmatlar mavjud"},
          "javob": "A"},
    192: {"savol": "Mikroyadro qanday holatda ishlashi mumkin?",
          "variantlar": {"A": "Tarqatilgan kompyuterlar orqali", "B": "Har doim offlayn", "C": "Faqat lokal tizimda",
                         "D": "Faqat sensorlarda"}, "javob": "A"},
    193: {"savol": "Qaysi OT arxitekturasi kengaytirish uchun eng mos?",
          "variantlar": {"A": "Modulliy", "B": "Statik", "C": "Monolit", "D": "Tizimli"}, "javob": "A"},
    194: {"savol": "Monolit tizimda har qanday o‘zgarish nimaga olib keladi?",
          "variantlar": {"A": "Butun tizimga ta’sir qiladi",
                         "B": "Faqat foydalanuvchi interfeysining ishdan chiqishiga",
                         "C": "Protsessorning ishlamay qolishiga", "D": "Hamma xizmatlar to‘xtaydi"}, "javob": "A"},
    195: {"savol": "Real vaqt OT’ning qanday arxitektura sinflari mavjud?",
          "variantlar": {"A": "To‘rtta: monolit, modul, mijoz-server, virtual", "B": "Faqat modul va yadro",
                         "C": "Faqat mijoz-server", "D": "Ikkita: sinxron va asinxron"}, "javob": "A"},
    196: {"savol": "Mikroyadrodagi serverlar qanday rejimda ishlaydi?",
          "variantlar": {"A": "Foydalanuvchi rejimida", "B": "Yadro rejimida", "C": "Interaktiv rejimda",
                         "D": "Grafik rejimda"}, "javob": "A"},
    197: {"savol": "Real vaqt OT qaysi sohalarda muhim hisoblanadi?",
          "variantlar": {"A": "Sanoat avtomatikasi va monitoringda", "B": "O‘yin sanoatida", "C": "Ofis dasturlarida",
                         "D": "Veb dasturlashda"}, "javob": "A"},
    198: {"savol": "Modullilik tizimga qanday imkon beradi?",
          "variantlar": {"A": "Tizimni o‘zgartirmasdan kengaytirish", "B": "Faqat bir nechta xizmat",
                         "C": "Faqat yadroga xizmat qo‘shish", "D": "Foydalanuvchi dasturlarini o‘zgartirish"},
          "javob": "A"},
    199: {"savol": "Operatsion tizim nima qiladi?",
          "variantlar": {"A": "Uskuna resurslarini boshqaradi", "B": "Faqat printerga ma’lumot yuboradi",
                         "C": "Grafik interfeysni chizadi", "D": "Tarmoqni o‘chiradi"}, "javob": "A"},
    200: {"savol": "Modulliy arxitekturadagi yuqori qatlam qanday kodga kirishi mumkin?",
          "variantlar": {"A": "Faqat o‘zidan pastdagi qatlamga", "B": "Faqat grafik interfeysga",
                         "C": "Har qanday pastki va yuqori qatlamga", "D": "Faqat operativ xotiraga"}, "javob": "A"},
    201: {"savol": "Real vaqt tizimining asosiy vazifalaridan biri nima?",
          "variantlar": {"A": "Real vaqt talablari asosida ishlash", "B": "Faqat grafik interfeysni chizish",
                         "C": "Videolarni tahrirlash", "D": "Katta hajmli ma'lumotlarni uzoq vaqt saqlash"},
          "javob": "A"},
    202: {"savol": "RV OT yadrosining sinxronizatsiya funksiyasi nima uchun kerak?",
          "variantlar": {"A": "Umumiy resurslarga bir vaqtning o‘zida kirishni cheklash uchun",
                         "B": "Protsessor tezligini avtomatik oshirish uchun",
                         "C": "Foydalanuvchi parolini saqlash uchun",
                         "D": "Operativ xotira hajmini kattalashtirish uchun"}, "javob": "A"},
    203: {"savol": "Eng ko‘p ishlatiladigan sinxronizatsiya vositasi nima?",
          "variantlar": {"A": "Ikkilik semafor", "B": "Kesh xotira", "C": "Lokal tarmoq", "D": "Dinamik xotira"},
          "javob": "A"},
    204: {"savol": "Real vaqt OT'larda \"masalalararo almashuv\" deganda nimani tushunamiz?",
          "variantlar": {"A": "Ma’lumotlarni ichki yoki tarmoq orqali uzatish", "B": "Elektr quvvatini taqsimlash",
                         "C": "Protsessorlarni almashtirish", "D": "Faqat qattiq diskdan o'qish"}, "javob": "A"},
    205: {"savol": "Datagrama orqali almashuv qanday hisoblanadi?",
          "variantlar": {"A": "Tez, lekin kafolatsiz", "B": "Sekin va 100% kafolatlangan",
                         "C": "Faqat fayllarni arxivlash", "D": "Mutlaqo xavfsiz va sekin"}, "javob": "A"},
    206: {"savol": "Real vaqt OT'da “axborotlarni taqsimlash” qanday amalga oshiriladi?",
          "variantlar": {"A": "Umumiy xotira va navbat tizimi orqali", "B": "Bluetooth orqali",
                         "C": "Faqat qog'ozga chop etish orqali", "D": "Ovozli xabarlar orqali"}, "javob": "A"},
    207: {"savol": "Drayverlar vazifasi nimada?",
          "variantlar": {"A": "Qurilmalar bilan ishlashni yengillashtirish", "B": "Protsessorni sovutish",
                         "C": "Dasturlarni o'chirish", "D": "Faqat internet tezligini oshirish"}, "javob": "A"},
    208: {"savol": "\"Muhim holatlar\" qanday bo‘lishi mumkin?",
          "variantlar": {"A": "Sinxron va asinxron", "B": "Katta va kichik", "C": "Ochiq va yopiq",
                         "D": "Simli va simsiz"}, "javob": "A"},
    209: {"savol": "Sinxron holat misoli sifatida nimani ko‘rsatish mumkin?",
          "variantlar": {"A": "USB ulanishi", "B": "Elektr toki uzilishi", "C": "Tasodifiy xatoliklar",
                         "D": "Apparatning buzilishi"}, "javob": "A"},
    210: {"savol": "OTning birinchi vazifasi nima?",
          "variantlar": {"A": "Kompyuter resurslarini boshqarish", "B": "Yangi dasturlash tilini yaratish",
                         "C": "Veb-saytlarni bloklash", "D": "Antivirus bazasini yangilash"}, "javob": "A"},
    211: {"savol": "Tizimli resursga misol bo‘la oladigan narsa qaysi?",
          "variantlar": {"A": "Protsessor vaqti", "B": "Foydalanuvchi rasmlari", "C": "O'yin fayllari",
                         "D": "Brauzer tarixi"}, "javob": "A"},
    212: {"savol": "Foydalanuvchi resursiga misol nima bo‘ladi?",
          "variantlar": {"A": "Fayl, jadval, grafik oyna", "B": "Operativ xotira mikrosxemasi",
                         "C": "Tizimli avtobus (bus)", "D": "Mikroprotsessor kesh xotirasi"}, "javob": "A"},
    213: {"savol": "API qisqartmasi nimani anglatadi?",
          "variantlar": {"A": "Application Programming Interface", "B": "Advanced Program Interface",
                         "C": "Applied Processor Integration", "D": "Automated Processing Input"}, "javob": "A"},
    214: {"savol": "Ko‘p masalalik qanday ishlaydi?",
          "variantlar": {"A": "Masalalar ustida parallel ishlaydi yoki foydalanuvchiga shunday tuyuladi",
                         "B": "Kompyuterni o'chirib yoqadi", "C": "Faqat bitta jarayonni sekin bajaradi",
                         "D": "Tarmoqqa ulanishni cheklaydi"}, "javob": "A"},
    215: {"savol": "“Jarayon” deganda nima tushuniladi?",
          "variantlar": {"A": "Dastur + unga ajratilgan resurslar", "B": "Faqat kompyuter qobig'i",
                         "C": "Internet tezligi", "D": "Faqatgina dastur kodi"}, "javob": "A"},
    216: {"savol": "Oqim (thread) nimani bildiradi?",
          "variantlar": {"A": "Dastur kodining bajariluvchi elementi", "B": "Elektr toki miqdori",
                         "C": "Tarmoqdagi ma'lumotlar o'chib ketishi", "D": "Faqat video signalni"}, "javob": "A"},
    217: {"savol": "Har bir jarayon eng kamida nechta oqimga ega bo‘ladi?",
          "variantlar": {"A": "1", "B": "0", "C": "5", "D": "Cheksiz"}, "javob": "A"},
    218: {"savol": "Ustunlik qanday belgilanadi?",
          "variantlar": {"A": "Rejalashtiruvchi tomonidan, son qiymat bilan", "B": "Tasodifiy sonlar generatori orqali",
                         "C": "Fayl nomi uzunligi orqali", "D": "Alifbo tartibida"}, "javob": "A"},
    219: {"savol": "Deskriptor qanday ma’lumotlarni o‘z ichiga oladi?",
          "variantlar": {"A": "Jarayon holati, ustunlik, registrlar holati", "B": "Rasm formati va o'lchamlari",
                         "C": "Tarmoq IP manzili va protokoli", "D": "Foydalanuvchi parollari"}, "javob": "A"},
    220: {"savol": "Reenterabellik nima?",
          "variantlar": {"A": "Vaqtincha uzilgan vazifani zarar qilmasdan davom ettirish", "B": "Dasturni o'chirish",
                         "C": "Xotirani to'liq tozalash", "D": "Internetga avtomatik ulanish"}, "javob": "A"},
    221: {"savol": "Arduino platformasi qaysi dasturlash tillariga asoslangan?",
          "variantlar": {"A": "C/C++", "B": "Java", "C": "Python va PHP", "D": "HTML/CSS"}, "javob": "A"},
    222: {"savol": "Arduino platformasining eng ko‘p tanilgan asosiy platasini ko‘rsating:",
          "variantlar": {"A": "UNO", "B": "Raspberry Pi", "C": "PLC x86", "D": "Intel Galileo"}, "javob": "A"},
    223: {"savol": "Arduino IDE dasturlash muhiti qanday dastur fayl kengaytmasini ishlatadi?",
          "variantlar": {"A": ".ino", "B": ".exe", "C": ".txt", "D": ".docx"}, "javob": "A"},
    224: {"savol": "Arduino dasturida majburiy bo‘lgan funksiyalar qaysilar?",
          "variantlar": {"A": "setup() va loop()", "B": "start() va stop()", "C": "begin() va end()",
                         "D": "main() va return()"}, "javob": "A"},
    225: {"savol": "Arduino Uno qaysi mikrokontroller asosida ishlaydi?",
          "variantlar": {"A": "ATmega328", "B": "Intel 8086", "C": "ARM Cortex-M4", "D": "ESP32"}, "javob": "A"},
    226: {"savol": "Arduino dasturlari kompilyatsiyalanayotganda, C++ dasturlash tili bilan qanday bog‘liq?",
          "variantlar": {"A": "Arduino preprotsessori C++ faylini tayyorlaydi",
                         "B": "Dastur faqat Python-ga o'giriladi", "C": "C++ ga umuman aloqasi yo'q",
                         "D": "Java baytkodiga kompilyatsiya qilinadi"}, "javob": "A"},
    227: {"savol": "Arduino platformasining apparat qismida nimalar mavjud emas?",
          "variantlar": {"A": "O‘yin interfeysi", "B": "USB port", "C": "Quvvat (pitaniya) bloki",
                         "D": "Kirish/chiqish (I/O) pinlari"}, "javob": "A"},
    228: {"savol": "“Shild” (shield) deganda nimani tushunasiz?",
          "variantlar": {"A": "Qo‘shimcha modul platalari", "B": "Himoya qopqog'i va korpus",
                         "C": "Antivirus dasturiy ta'minoti", "D": "Faqat sensorlar to'plami"}, "javob": "A"},
    229: {"savol": "Ethernet Shield vazifasi nima?",
          "variantlar": {"A": "Internetga ulanishni ta’minlash", "B": "Operativ xotirani oshirish",
                         "C": "Monitorda tasvirni ko'rsatish", "D": "Batareya quvvatini uzaytirish"}, "javob": "A"},
    230: {"savol": "Arduino Fio platasining asosiy xususiyati nima?",
          "variantlar": {"A": "Simsiz tatbiqlar uchun mo‘ljallangan", "B": "Suv ostida ishlash uchun",
                         "C": "Faqat sanoat dvigatellarida ishlatiladi", "D": "Kosmik stansiyalar uchun mo'ljallangan"},
          "javob": "A"},
    231: {"savol": "LilyPad platasining o‘ziga xos jihati nima?",
          "variantlar": {"A": "Matoga tikilishi mumkin", "B": "Olovga mutlaqo chidamli", "C": "Eng katta o'lchamga ega",
                         "D": "Displeyi mavjud"}, "javob": "A"},
    232: {"savol": "Arduino Due qaysi protsessor asosida ishlaydi?",
          "variantlar": {"A": "ARM Cortex-M3", "B": "ATmega16", "C": "Intel Core i3", "D": "ESP8266"}, "javob": "A"},
    233: {"savol": "ARM protsessorlarining ilk modeli qachon yaratilgan?",
          "variantlar": {"A": "1986", "B": "2000", "C": "2010", "D": "1970"}, "javob": "A"},
    234: {"savol": "ARM arxitekturasining qaysi liniyasi real vaqt tizimlari uchun mo‘ljallangan?",
          "variantlar": {"A": "Cortex-R", "B": "Cortex-A", "C": "Cortex-M", "D": "Cortex-X"}, "javob": "A"},
    235: {"savol": "Arduino platformasi dastlab kimlar uchun mo‘ljallangan edi?",
          "variantlar": {"A": "Boshlovchi va havaskorlar", "B": "Katta korporatsiyalar", "C": "Kosmik agentliklar",
                         "D": "Faqat yirik zavodlar uchun"}, "javob": "A"},
    236: {"savol": "Arduino UNO platasi USB orqali qanday interfeysdan foydalanadi?",
          "variantlar": {"A": "FTDI", "B": "HDMI", "C": "VGA", "D": "PS/2"}, "javob": "A"},
    237: {"savol": "Arduino IDE ning asosiy afzalligi nima?",
          "variantlar": {"A": "Oddiy interfeys va tez kompilyatsiya",
                         "B": "Juda og'ir tizim resurslarini talab qilishi",
                         "C": "Faqat pullik litsenziya bilan ishlashi", "D": "Murakkab 3D modellashtirish kiritilgani"},
          "javob": "A"},
    238: {"savol": "Arduino mikrokontrollerlarini dasturlashda yuklovchi (bootloader) vazifasi nima?",
          "variantlar": {"A": "Dasturiy yozish qurilmasisiz dasturlash imkonini beradi",
                         "B": "Faqat o'yinlarni ishga tushiradi", "C": "Kompyuterni viruslardan himoya qiladi",
                         "D": "Xotira hajmini jismoniy oshiradi"}, "javob": "A"},
    239: {"savol": "MP3 Shield qanday imkoniyat beradi?",
          "variantlar": {"A": "MP3 fayllarni o‘qish va yozish", "B": "Videolarni tahrirlash",
                         "C": "Matnlarni tarjima qilish", "D": "Wi-Fi tarmog'ini yaratish"}, "javob": "A"},
    240: {"savol": "Arduino platformasining qanday sohalarda keng qo‘llaniladi?",
          "variantlar": {"A": "Elektronika, avtomatika, IoT, sanoat", "B": "Faqat adabiyot va falsafada",
                         "C": "Faqat kiyim-kechak dizaynida", "D": "Faqat pishiriqlar pishirishda"}, "javob": "A"},
    241: {"savol": "Tizimli dasturiy ta’minotning asosiy vazifasi nima?",
          "variantlar": {"A": "Kompyuter resurslarini boshqarish", "B": "Matnli hujjatlarni yaratish",
                         "C": "Suratlarni tahrirlash", "D": "Veb-saytlarni yuklash"}, "javob": "A"},
    242: {"savol": "Amaliy dasturiy ta’minot nimaga mo‘ljallangan?",
          "variantlar": {"A": "Foydalanuvchi vazifalarini bajarishga", "B": "Operativ xotirani tozalashga",
                         "C": "Tizim drayverlarini yangilashga", "D": "Protsessor chastotasini oshirishga"},
          "javob": "A"},
    243: {"savol": "Instrumental dasturiy ta’minot nimani ta’minlaydi?",
          "variantlar": {"A": "Yangi dasturlar yaratish va sinash imkoniyatini",
                         "B": "Antivirus bazalarini yangilashni", "C": "O'yinlarni onlayn o'ynashni",
                         "D": "Qurilmalarni jismoniy ta'mirlashni"}, "javob": "A"},
    244: {"savol": "Mikrokontrollerli tizimlarda tizimli DT nimani boshqaradi?",
          "variantlar": {"A": "Hisoblash jarayonini va uning nazoratini", "B": "Foydalanuvchi akkauntlarini",
                         "C": "Grafik monitor ruxsatini", "D": "Faqat tashqi audioni"}, "javob": "A"},
    245: {"savol": "Amaliy DTda o‘lchov moduli vazifasi nima?",
          "variantlar": {"A": "Datchiklardan real holatni olish", "B": "Ma'lumotlarni o'chirib tashlash",
                         "C": "Yangi parol o'rnatish", "D": "Qurilma narxini hisoblash"}, "javob": "A"},
    246: {"savol": "Boshqaruvchi modul nima qiladi?",
          "variantlar": {"A": "Talab va real holatni taqqoslaydi va ta’sir hosil qiladi",
                         "B": "O'yin grafikalarini chizadi", "C": "Faqat brauzerni ishga tushiradi",
                         "D": "Fayllarni internetdan tortadi"}, "javob": "A"},
    247: {"savol": "Instrumental DT tarkibiga nimalar kiradi?",
          "variantlar": {"A": "Translyator, sozlash vositalari", "B": "Video pleyerlar va brauzerlar",
                         "C": "Matn muharrirlari va ofis dasturlari", "D": "Antiviruslar va xavfsizlik devorlari"},
          "javob": "A"},
    248: {"savol": "Amaliy dasturiy ta’minotning modullari qanday asosda quriladi?",
          "variantlar": {"A": "Modulliy tamoyil asosida", "B": "Kaskad tamoyil asosida",
                         "C": "Tasodifiy tamoyil asosida", "D": "Yagona monolit tarzda"}, "javob": "A"},
    249: {"savol": "Dasturiy ta’minotni yaratishning birinchi bosqichi nima?",
          "variantlar": {"A": "Vazifalarni aniqlash va tahlil", "B": "To'g'ridan-to'g'ri kod yozishni boshlash",
                         "C": "Dasturni ommaga sotish", "D": "Serverlarni o'chirish"}, "javob": "A"},
    250: {"savol": "Tashxislash dasturlari nima uchun ishlatiladi?",
          "variantlar": {"A": "Mikrokontrollerli tizimning to‘g‘ri ishlashini tekshirish uchun",
                         "B": "Xakerlik hujumlarini uyushtirish uchun", "C": "Rasm chizish uchun",
                         "D": "Internet tezligini oshirish uchun"}, "javob": "A"},
    251: {"savol": "Foydalanuvchi dasturiy ta’minotining asosiy maqsadi nima?",
          "variantlar": {"A": "Foydalanuvchining amaliy topshiriqlarini bajarish", "B": "Qurilmani blokirovka qilish",
                         "C": "OTni o'z-o'zidan yangilash", "D": "Drayverlarni arxivlash"}, "javob": "A"},
    252: {"savol": "Operatsion tizim yadrosining asosiy xususiyati nima?",
          "variantlar": {"A": "Ustunlikka asoslangan uzilishlarni boshqarish", "B": "Faqat ranglarni sozlash",
                         "C": "Matnli xabarlarni yuborish", "D": "Ovoz balandligini pasaytirish"}, "javob": "A"},
    253: {"savol": "Amaliy DT foydalanuvchiga nima beradi?",
          "variantlar": {"A": "Ma’lumotni vizual ko‘rsatish, saqlash", "B": "BIOS sozlamalariga kirish huquqini",
                         "C": "To'g'ridan-to'g'ri yadro kodini o'zgartirishni", "D": "Tarmoqni uzib qo'yish imkonini"},
          "javob": "A"},
    254: {"savol": "Tizimli DTga misol bo‘la oladi:",
          "variantlar": {"A": "Linux yadro", "B": "Microsoft Word", "C": "Adobe Photoshop", "D": "Telegram messenjeri"},
          "javob": "A"},
    255: {"savol": "Amaliy DT tarkibidagi beruvchi modul vazifasi:",
          "variantlar": {"A": "Talab etilgan holatni belgilash", "B": "Operativ xotirani tozalash",
                         "C": "Qurilmani jismoniy sovutish", "D": "Internet trafigini o'lchash"}, "javob": "A"},
    256: {"savol": "Instrumental DT xatoliklarni qanday hal qiladi?",
          "variantlar": {"A": "Sinash va tuzatish vositalari yordamida", "B": "Kodni butunlay o'chirib tashlaydi",
                         "C": "Kompyuterni qayta yuklash orqali", "D": "Tarmoqqa ulanishni cheklash bilan"},
          "javob": "A"},
    257: {"savol": "Dasturiy ta’minotni yaratishda “joylashtiruvchi dastur” vazifasi:",
          "variantlar": {"A": "Dastur modullarini xotiraga joylashtirish", "B": "Spam xabarlarni filtrlash",
                         "C": "Musiqa fayllarini ochish", "D": "Qattiq diskni formatlash"}, "javob": "A"},
    258: {"savol": "Amaliy DT foydalanuvchi bilan qanday aloqada bo‘ladi?",
          "variantlar": {"A": "Modullar orqali muloqatda", "B": "Faqat ovozli signallar orqali",
                         "C": "Faqat printerdan qog'oz chiqarib", "D": "To'g'ridan-to'g'ri mikroprotsessor orqali"},
          "javob": "A"},
    259: {"savol": "Instrumental DTda \"translyator\" vazifasi nima?",
          "variantlar": {"A": "Yuqori darajadagi dastur tilini mashina kodiga aylantirish",
                         "B": "Matnlarni chet tillariga tarjima qilish", "C": "Rasmlarni siqib hajmini kamaytirish",
                         "D": "Tarmoq manzillarini yashirish"}, "javob": "A"},
    260: {"savol": "Dasturiy ta’minotni loyihalashda yakuniy bosqich nima?",
          "variantlar": {"A": "Dasturdan foydalanishga topshirish va mualliflik nazorati",
                         "B": "Muammolarni tahlil qilish", "C": "Dastlabki kodni endigina yozish",
                         "D": "Foydalanuvchi interfeysi eskizini chizish"}, "javob": "A"},
    261: {"savol": "Mikrokontrollerli tizimlarni sozlashning asosiy maqsadi nima?",
          "variantlar": {"A": "Tizimni to‘g‘ri ishlashini ta’minlash",
                         "B": "Elektr quvvatini eng yuqori darajaga ko'tarish", "C": "Tizimni atayin ishdan chiqarish",
                         "D": "Dasturiy ta'minotni butunlay o'chirish"}, "javob": "A"},
    262: {"savol": "Sozlashning dasturiy vositalariga nimalar kiradi?",
          "variantlar": {"A": "Modellashtirish tizimi", "B": "Kavsharlagich (payalnik)",
                         "C": "Multimetr va ossillograf", "D": "Jismoniy datchiklar"}, "javob": "A"},
    263: {"savol": "Multimetrning vazifasi nima?",
          "variantlar": {"A": "Kuchlanish, tok va qarshilikni o‘lchash", "B": "Havoning namligini o'lchash",
                         "C": "Tizimdagi viruslarni topish", "D": "Fayllarning hajmini o'lchash"}, "javob": "A"},
    264: {"savol": "Ossillograf qanday signallarni ko‘rsatadi?",
          "variantlar": {"A": "Elektr signalining vaqtga bog‘liqligi", "B": "Atrof-muhit haroratining o'zgarishi",
                         "C": "Internet tezligi grafiklari", "D": "Xotirada band qilingan joy miqdori"}, "javob": "A"},
    265: {"savol": "Chastotomer nima uchun ishlatiladi?",
          "variantlar": {"A": "Signal chastotasini aniqlash", "B": "Qurilmaning og'irligini hisoblash",
                         "C": "Boltlarning mahkamligini tekshirish", "D": "Kuchlanishni nolga tushirish"},
          "javob": "A"},
    266: {"savol": "Mantiqiy tekshiruvchining asosiy vazifasi nima?",
          "variantlar": {"A": "Raqamli signallarning mantiqiy qiymatini tekshirish",
                         "B": "Matn hujjatlaridagi xatolarni to'g'irlash", "C": "Internet ulanish tezligini o'lchash",
                         "D": "Ovoz chastotasini o'zgartirish"}, "javob": "A"},
    267: {"savol": "Impulslar generatori qanday holatlarda ishlatiladi?",
          "variantlar": {"A": "Raqamli tizimga tashqi ta’sirni o‘rganishda", "B": "Suratlarga effektlar qo'shishda",
                         "C": "Matnlarni avtomatik o'qishda", "D": "Fayllarni arxivdan chiqarishda"}, "javob": "A"},
    268: {"savol": "Impulslar generatori nima hosil qiladi?",
          "variantlar": {"A": "Qisqa kuchli impulslar", "B": "To'xtovsiz doimiy tok",
                         "C": "Yuqori chastotali radiatsiya", "D": "Lazer nurlari"}, "javob": "A"},
    269: {"savol": "Sozlashda foydalaniladigan umumtexnik vositalar qaysilar?",
          "variantlar": {"A": "Multimetr, chastotomer, ossillograf", "B": "Qattiq disk, RAM, kuler",
                         "C": "Sichqoncha, klaviatura, monitor", "D": "Printer, skaner, faks"}, "javob": "A"},
    270: {"savol": "Dasturiy model (simulyator) qanday maqsadga xizmat qiladi?",
          "variantlar": {"A": "Mikrokontroller tizimini simulyatsiya qilish uchun", "B": "Hujjatlarni chop etish uchun",
                         "C": "Viruslarni tozalash uchun", "D": "Qurilma dizaynini 3D formatda ko'rish uchun"},
          "javob": "A"},
    271: {"savol": "Simulyator yordamida foydalanuvchi nima qila oladi?",
          "variantlar": {"A": "Dasturni ishga tushiradi va to‘xtatadi", "B": "Mikrosxemani jismonan ta'mirlaydi",
                         "C": "Qurilma qizib ketishining oldini oladi", "D": "Internet orqali kino ko'radi"},
          "javob": "A"},
    272: {"savol": "DXQ emulyatori nima qiladi?",
          "variantlar": {"A": "Mikrokontroller tizimini apparat darajasida sozlaydi",
                         "B": "Foydalanuvchi uchun veb-sayt yaratadi", "C": "Musiqa fayllarini tahrirlaydi",
                         "D": "Tasvirlarni turli formatlarga o'zgartiradi"}, "javob": "A"},
    273: {"savol": "Dasturlash qurilmasining asosiy vazifasi nima?",
          "variantlar": {"A": "Mikrokontrollerga dasturni doimiy hotiraga yozish", "B": "Ekranni yorug'ligini sozlash",
                         "C": "Fayllarni vaqtincha saqlash", "D": "Printer orqali qog'oz chiqarish"}, "javob": "A"},
    274: {"savol": "Emulyatsiyalanadigan mikrokontroller tizimida nima kuzatiladi?",
          "variantlar": {"A": "Hotira qiymatlari va tashqi uzellar holati", "B": "Protsessorning tashqi harorati",
                         "C": "Foydalanuvchining bosgan tugmalari tartibi", "D": "Faqat kompyuter soatining ishlashi"},
          "javob": "A"},
    275: {"savol": "Dasturlash qurilmasi orqali dastur qayerga yoziladi?",
          "variantlar": {"A": "Mikrokontrollerning doimiy hotirasiga", "B": "Monitor kesh xotirasiga",
                         "C": "Router flesh xotirasiga", "D": "Faqat klaviatura xotirasiga"}, "javob": "A"},
    276: {"savol": "Mantiqiy signalni noaniqlik xududida bo‘lishi nimani bildiradi?",
          "variantlar": {"A": "Noto‘g‘ri ishlash ehtimolini", "B": "Tizimning juda tez ishlashini",
                         "C": "Quvvat sarfi umuman yo'qligini", "D": "Dasturning mutlaqo to'g'riligini"}, "javob": "A"},
    277: {"savol": "Simulyator qanday buyrug‘ asosida ishlaydi?",
          "variantlar": {"A": "Mikrokontroller protsessorining har bir buyrug‘i bilan",
                         "B": "Foydalanuvchi ovozli ko'rsatmasi bilan", "C": "Matnli brauzer buyruqlari bilan",
                         "D": "Faqat sichqonchaning o'ng tugmasi orqali"}, "javob": "A"},
    278: {"savol": "Dasturlash qurilmasining ishlash turi nimalarga bog‘liq?",
          "variantlar": {"A": "Doimiy hotira turi va ulanish usuliga", "B": "Xonaning namlik darajasiga",
                         "C": "Klaviatura tiliga", "D": "Ekranning o'lchamlariga"}, "javob": "A"},
    279: {"savol": "Mantiqiy tekshiruvchi nimalarni tekshiradi?",
          "variantlar": {"A": "Raqamli qiymatlarning to‘g‘riligini", "B": "Veb-saytlardagi havolalarni",
                         "C": "Foydalanuvchi matnining imlosini", "D": "Ovozli signallarning chastotasini"},
          "javob": "A"},
    280: {"savol": "Tashxislashning dasturiy vositalari qaysi holatlarda foydali?",
          "variantlar": {"A": "Tizim ishlashini tahlil qilish va nosozlikni aniqlashda",
                         "B": "Yangi o'yin yaratish jarayonida", "C": "Katta matnli ma'lumotlarni tarjima qilishda",
                         "D": "Suratlarga badiiy ishlov berishda"}, "javob": "A"},
    281: {"savol": "Generativ sun’iy intellekt (GAI) nima qiladi?",
          "variantlar": {"A": "Yangi kontent yaratadi", "B": "Kompyuterlarni jismoniy ta'mirlaydi",
                         "C": "Operatsion tizimlarni o'chiradi", "D": "Faqat viruslarni aniqlaydi"}, "javob": "A"},
    282: {"savol": "Tabiiy tilni qayta ishlash (NLP) texnologiyasining vazifasi nima?",
          "variantlar": {"A": "Inson va kompyuter o‘rtasidagi muloqotni soddalashtirish",
                         "B": "Tarmoq tezligini ikki barobar oshirish", "C": "Xotira hajmini siqish",
                         "D": "Apparat qurilmalarini yig'ish"}, "javob": "A"},
    283: {"savol": "AlphaFold 2 dasturi nima bilan bog‘liq?",
          "variantlar": {"A": "Protein strukturasini tahlil qilish", "B": "Yangi video o'yinlar yaratish",
                         "C": "Bulutli saqlash hajmini boshqarish", "D": "Dronlarni boshqarish protokoli"},
          "javob": "A"},
    284: {"savol": "Tesla FSD texnologiyasi nima bilan bog‘liq?",
          "variantlar": {"A": "Avtonom transport vositalari", "B": "Robot-ofitsiantlar dizayni",
                         "C": "Buxgalteriya hisobotlarini tuzish", "D": "Mobil telefonlar operatsion tizimi"},
          "javob": "A"},
    285: {"savol": "Kvant kompyuterlarda ishlatiladigan asosiy birlik nima?",
          "variantlar": {"A": "Kubit", "B": "Bayt", "C": "Kilobayt", "D": "Piksel"}, "javob": "A"},
    286: {"savol": "Kubit qanday xususiyatga ega?",
          "variantlar": {"A": "Bir vaqtning o‘zida 0 va 1 holatda bo‘lishi mumkin",
                         "B": "Faqat doimiy 0 holatini saqlaydi", "C": "Faqat 1 holatini saqlaydi",
                         "D": "Harflarni ifodalash uchun ishlatiladi"}, "javob": "A"},
    287: {"savol": "Kvant bog‘liqlik nimani anglatadi?",
          "variantlar": {"A": "Bir kubit holati boshqalariga ta’sir qiladi",
                         "B": "Simsiz tarmoq orqali ulanish imkoniyati", "C": "Kompyuter va inson fikri bog'lanishi",
                         "D": "Elektr quvvati orqali quvvatlanish"}, "javob": "A"},
    288: {"savol": "Kvant kompyuterlar qanday sohalarda qo‘llaniladi?",
          "variantlar": {"A": "Kriptografiya, tibbiyot, optimallashtirish", "B": "Faqat veb-dizaynda",
                         "C": "Faqat oddiy ofis dasturlarida", "D": "Faqat musiqiy kompozitsiyalar yaratishda"},
          "javob": "A"},
    289: {"savol": "Zamonaviy kompyuter tizimlarining xususiyati nima?",
          "variantlar": {"A": "Ko‘p yadroli va sun’iy intellekt integratsiyasi mavjud",
                         "B": "Ularda umuman xotira ishlatilmaydi", "C": "Faqat bir yadroli ishlov berishadi",
                         "D": "Klaviatura va sichqonchasiz ishlamaydi"}, "javob": "A"},
    290: {"savol": "Bulutli texnologiyaning afzalligi nima?",
          "variantlar": {"A": "Har qanday joydan ma’lumotlarga kirish imkoniyati",
                         "B": "Ma'lumotlarni faqat qattiq diskda saqlashi", "C": "Faqat simli internet orqali ishlashi",
                         "D": "Internet tezligini sekinlashtirishi"}, "javob": "A"},
    291: {"savol": "IoT deganda nimani tushunasiz?",
          "variantlar": {"A": "Internet orqali ulangan narsalar", "B": "Televizorlar uchun yangi avlod kanallari",
                         "C": "Internet xizmati provayderi (ISP)", "D": "Maxsus dasturlash tili"}, "javob": "A"},
    292: {"savol": "O‘rnatilgan tizimlar qanday xususiyatga ega?",
          "variantlar": {"A": "Aniq vazifaga yo‘naltirilgan, ixcham", "B": "Umumiy maqsadli va juda katta o'lchamli",
                         "C": "Faqat uyinlar uchun mo'ljallangan yuqori grafika",
                         "D": "Tashqi quvvat manbaisiz ishlash imkonsizligi"}, "javob": "A"},
    293: {"savol": "O‘rnatilgan tizimlar ko‘p hollarda qanday tizim asosida ishlaydi?",
          "variantlar": {"A": "Real vaqt operatsion tizimi (RTOS)", "B": "Windows 11", "C": "MacOS", "D": "MS-DOS"},
          "javob": "A"},
    294: {"savol": "O‘rnatilgan tizimlarda qaysi mikrokontrollerlardan foydalaniladi?",
          "variantlar": {"A": "STM32, ESP32, ARM Cortex", "B": "Intel Core i9, AMD Ryzen", "C": "Nvidia RTX 4090",
                         "D": "Apple M2 Max"}, "javob": "A"},
    295: {"savol": "Aktuator nima?",
          "variantlar": {"A": "Harakat hosil qiluvchi qurilma", "B": "Haroratni sezuvchi datchik",
                         "C": "Faqat dasturlash tili kodi", "D": "Bulutli saqlash serveri"}, "javob": "A"},
    296: {"savol": "RTOS namunalariga qaysilar kiradi?",
          "variantlar": {"A": "FreeRTOS, VxWorks, QNX", "B": "Adobe Photoshop, Premiere Pro",
                         "C": "Microsoft Office to'plami", "D": "Google Chrome, Mozilla Firefox"}, "javob": "A"},
    297: {"savol": "Dasturlash tillaridan qaysilari o‘rnatilgan tizimlarda keng qo‘llaniladi?",
          "variantlar": {"A": "C, C++, Python", "B": "HTML, CSS, JavaScript", "C": "SQL, MongoDB", "D": "Ruby, Swift"},
          "javob": "A"},
    298: {"savol": "Arduino IDE nima uchun ishlatiladi?",
          "variantlar": {"A": "Mikrokontroller dasturini yozish uchun", "B": "3D modellar yaratish uchun",
                         "C": "Moliyaviy hisobotlar tuzish uchun", "D": "Video montaj ishlari uchun"}, "javob": "A"},
    299: {"savol": "Proteus dasturining vazifasi nima?",
          "variantlar": {"A": "Elektron sxemani chizish va simulyatsiya qilish",
                         "B": "Murakkab video tahrir va montaj qilish",
                         "C": "Matnlarni avtomatlashtirilgan tarzda tarjima qilish",
                         "D": "Operatsion tizimlarni yangidan o'rnatish"}, "javob": "A"},
    300: {"savol": "O‘rnatilgan tizimlar qaysi sohalarda qo‘llaniladi?",
          "variantlar": {"A": "IoT, sanoat, tibbiyot, transport", "B": "Faqat sartaroshlik va go'zallik salonlarida",
                         "C": "Faqat maktabdagi adabiyot darslarida", "D": "Faqat rangtasvir san'atida"}, "javob": "A"},
    301: {"savol": "O‘rnatilgan tizimlar qaysi sohalarda qo‘llaniladi?",
          "variantlar": {"A": "IoT, sanoat, tibbiyot, transport", "B": "Faqat sartaroshlik va go'zallik salonlarida",
                         "C": "Faqat maktabdagi adabiyot darslarida", "D": "Faqat rangtasvir san'atida"}, "javob": "A"}
}
